package uk.co.carefulcoder.date
case class TimeZone(id: String)

object TimeZone {
  object Australia {
    type Victoria = Victoria.type
    type Brisbane = Brisbane.type
    type NSW = NSW.type
    type Lindeman = Lindeman.type
    type Melbourne = Melbourne.type
    type Darwin = Darwin.type
    type Sydney = Sydney.type
    type ACT = ACT.type
    type BrokenHill = BrokenHill.type
    type Tasmania = Tasmania.type
    type Currie = Currie.type
    type West = West.type
    type Eucla = Eucla.type
    type Hobart = Hobart.type
    type Yancowinna = Yancowinna.type
    type South = South.type
    type LordHowe = LordHowe.type
    type Canberra = Canberra.type
    type Perth = Perth.type
    type Queensland = Queensland.type
    type LHI = LHI.type
    type Adelaide = Adelaide.type
    type North = North.type
    
    implicit object Victoria extends TimeZone(id = "Australia/Victoria")
    implicit object Brisbane extends TimeZone(id = "Australia/Brisbane")
    implicit object NSW extends TimeZone(id = "Australia/NSW")
    implicit object Lindeman extends TimeZone(id = "Australia/Lindeman")
    implicit object Melbourne extends TimeZone(id = "Australia/Melbourne")
    implicit object Darwin extends TimeZone(id = "Australia/Darwin")
    implicit object Sydney extends TimeZone(id = "Australia/Sydney")
    implicit object ACT extends TimeZone(id = "Australia/ACT")
    implicit object BrokenHill extends TimeZone(id = "Australia/Broken_Hill")
    implicit object Tasmania extends TimeZone(id = "Australia/Tasmania")
    implicit object Currie extends TimeZone(id = "Australia/Currie")
    implicit object West extends TimeZone(id = "Australia/West")
    implicit object Eucla extends TimeZone(id = "Australia/Eucla")
    implicit object Hobart extends TimeZone(id = "Australia/Hobart")
    implicit object Yancowinna extends TimeZone(id = "Australia/Yancowinna")
    implicit object South extends TimeZone(id = "Australia/South")
    implicit object LordHowe extends TimeZone(id = "Australia/Lord_Howe")
    implicit object Canberra extends TimeZone(id = "Australia/Canberra")
    implicit object Perth extends TimeZone(id = "Australia/Perth")
    implicit object Queensland extends TimeZone(id = "Australia/Queensland")
    implicit object LHI extends TimeZone(id = "Australia/LHI")
    implicit object Adelaide extends TimeZone(id = "Australia/Adelaide")
    implicit object North extends TimeZone(id = "Australia/North")
  }
  object Europe {
    type Berlin = Berlin.type
    type Ljubljana = Ljubljana.type
    type Sarajevo = Sarajevo.type
    type Busingen = Busingen.type
    type IsleOfMan = IsleOfMan.type
    type Bratislava = Bratislava.type
    type Luxembourg = Luxembourg.type
    type Lisbon = Lisbon.type
    type Vienna = Vienna.type
    type Dublin = Dublin.type
    type Sofia = Sofia.type
    type Chisinau = Chisinau.type
    type Moscow = Moscow.type
    type Zaporozhye = Zaporozhye.type
    type Istanbul = Istanbul.type
    type Monaco = Monaco.type
    type Budapest = Budapest.type
    type Tiraspol = Tiraspol.type
    type Belfast = Belfast.type
    type Gibraltar = Gibraltar.type
    type Minsk = Minsk.type
    type Brussels = Brussels.type
    type Copenhagen = Copenhagen.type
    type Belgrade = Belgrade.type
    type Zagreb = Zagreb.type
    type Bucharest = Bucharest.type
    type Andorra = Andorra.type
    type Vatican = Vatican.type
    type Kaliningrad = Kaliningrad.type
    type Samara = Samara.type
    type Riga = Riga.type
    type Oslo = Oslo.type
    type Rome = Rome.type
    type Tirane = Tirane.type
    type Prague = Prague.type
    type London = London.type
    type Stockholm = Stockholm.type
    type Zurich = Zurich.type
    type SanMarino = SanMarino.type
    type Simferopol = Simferopol.type
    type Tallinn = Tallinn.type
    type Jersey = Jersey.type
    type Helsinki = Helsinki.type
    type Guernsey = Guernsey.type
    type Madrid = Madrid.type
    type Uzhgorod = Uzhgorod.type
    type Amsterdam = Amsterdam.type
    type Podgorica = Podgorica.type
    type Vaduz = Vaduz.type
    type Malta = Malta.type
    type Volgograd = Volgograd.type
    type Mariehamn = Mariehamn.type
    type Vilnius = Vilnius.type
    type Athens = Athens.type
    type Skopje = Skopje.type
    type Warsaw = Warsaw.type
    type Nicosia = Nicosia.type
    type Paris = Paris.type
    type Kiev = Kiev.type
    implicit object Berlin extends TimeZone(id = "Europe/Berlin")
    implicit object Ljubljana extends TimeZone(id = "Europe/Ljubljana")
    implicit object Sarajevo extends TimeZone(id = "Europe/Sarajevo")
    implicit object Busingen extends TimeZone(id = "Europe/Busingen")
    implicit object IsleOfMan extends TimeZone(id = "Europe/Isle_of_Man")
    implicit object Bratislava extends TimeZone(id = "Europe/Bratislava")
    implicit object Luxembourg extends TimeZone(id = "Europe/Luxembourg")
    implicit object Lisbon extends TimeZone(id = "Europe/Lisbon")
    implicit object Vienna extends TimeZone(id = "Europe/Vienna")
    implicit object Dublin extends TimeZone(id = "Europe/Dublin")
    implicit object Sofia extends TimeZone(id = "Europe/Sofia")
    implicit object Chisinau extends TimeZone(id = "Europe/Chisinau")
    implicit object Moscow extends TimeZone(id = "Europe/Moscow")
    implicit object Zaporozhye extends TimeZone(id = "Europe/Zaporozhye")
    implicit object Istanbul extends TimeZone(id = "Europe/Istanbul")
    implicit object Monaco extends TimeZone(id = "Europe/Monaco")
    implicit object Budapest extends TimeZone(id = "Europe/Budapest")
    implicit object Tiraspol extends TimeZone(id = "Europe/Tiraspol")
    implicit object Belfast extends TimeZone(id = "Europe/Belfast")
    implicit object Gibraltar extends TimeZone(id = "Europe/Gibraltar")
    implicit object Minsk extends TimeZone(id = "Europe/Minsk")
    implicit object Brussels extends TimeZone(id = "Europe/Brussels")
    implicit object Copenhagen extends TimeZone(id = "Europe/Copenhagen")
    implicit object Belgrade extends TimeZone(id = "Europe/Belgrade")
    implicit object Zagreb extends TimeZone(id = "Europe/Zagreb")
    implicit object Bucharest extends TimeZone(id = "Europe/Bucharest")
    implicit object Andorra extends TimeZone(id = "Europe/Andorra")
    implicit object Vatican extends TimeZone(id = "Europe/Vatican")
    implicit object Kaliningrad extends TimeZone(id = "Europe/Kaliningrad")
    implicit object Samara extends TimeZone(id = "Europe/Samara")
    implicit object Riga extends TimeZone(id = "Europe/Riga")
    implicit object Oslo extends TimeZone(id = "Europe/Oslo")
    implicit object Rome extends TimeZone(id = "Europe/Rome")
    implicit object Tirane extends TimeZone(id = "Europe/Tirane")
    implicit object Prague extends TimeZone(id = "Europe/Prague")
    implicit object London extends TimeZone(id = "Europe/London")
    implicit object Stockholm extends TimeZone(id = "Europe/Stockholm")
    implicit object Zurich extends TimeZone(id = "Europe/Zurich")
    implicit object SanMarino extends TimeZone(id = "Europe/San_Marino")
    implicit object Simferopol extends TimeZone(id = "Europe/Simferopol")
    implicit object Tallinn extends TimeZone(id = "Europe/Tallinn")
    implicit object Jersey extends TimeZone(id = "Europe/Jersey")
    implicit object Helsinki extends TimeZone(id = "Europe/Helsinki")
    implicit object Guernsey extends TimeZone(id = "Europe/Guernsey")
    implicit object Madrid extends TimeZone(id = "Europe/Madrid")
    implicit object Uzhgorod extends TimeZone(id = "Europe/Uzhgorod")
    implicit object Amsterdam extends TimeZone(id = "Europe/Amsterdam")
    implicit object Podgorica extends TimeZone(id = "Europe/Podgorica")
    implicit object Vaduz extends TimeZone(id = "Europe/Vaduz")
    implicit object Malta extends TimeZone(id = "Europe/Malta")
    implicit object Volgograd extends TimeZone(id = "Europe/Volgograd")
    implicit object Mariehamn extends TimeZone(id = "Europe/Mariehamn")
    implicit object Vilnius extends TimeZone(id = "Europe/Vilnius")
    implicit object Athens extends TimeZone(id = "Europe/Athens")
    implicit object Skopje extends TimeZone(id = "Europe/Skopje")
    implicit object Warsaw extends TimeZone(id = "Europe/Warsaw")
    implicit object Nicosia extends TimeZone(id = "Europe/Nicosia")
    implicit object Paris extends TimeZone(id = "Europe/Paris")
    implicit object Kiev extends TimeZone(id = "Europe/Kiev")
  }
  object Asia {
    type Urumqi = Urumqi.type
    type Damascus = Damascus.type
    type Ulaanbaatar = Ulaanbaatar.type
    type Ashgabat = Ashgabat.type
    type Jakarta = Jakarta.type
    type Tokyo = Tokyo.type
    type Muscat = Muscat.type
    type Hovd = Hovd.type
    type Rangoon = Rangoon.type
    type Qyzylorda = Qyzylorda.type
    type Macau = Macau.type
    type Pyongyang = Pyongyang.type
    type Anadyr = Anadyr.type
    type Chungking = Chungking.type
    type Yekaterinburg = Yekaterinburg.type
    type Qatar = Qatar.type
    type HongKong = HongKong.type
    type Kamchatka = Kamchatka.type
    type Bishkek = Bishkek.type
    type Calcutta = Calcutta.type
    type Beirut = Beirut.type
    type Makassar = Makassar.type
    type Dushanbe = Dushanbe.type
    type Vientiane = Vientiane.type
    type Istanbul = Istanbul.type
    type Taipei = Taipei.type
    type Colombo = Colombo.type
    type Shanghai = Shanghai.type
    type Saigon = Saigon.type
    type Chongqing = Chongqing.type
    type Macao = Macao.type
    type Bangkok = Bangkok.type
    type Oral = Oral.type
    type Kuwait = Kuwait.type
    type Dubai = Dubai.type
    type Katmandu = Katmandu.type
    type Irkutsk = Irkutsk.type
    type Seoul = Seoul.type
    type Pontianak = Pontianak.type
    type Kuching = Kuching.type
    type Tashkent = Tashkent.type
    type Riyadh = Riyadh.type
    type Dili = Dili.type
    type TelAviv = TelAviv.type
    type PhnomPenh = PhnomPenh.type
    type Yakutsk = Yakutsk.type
    type Gaza = Gaza.type
    type Manila = Manila.type
    type Thimbu = Thimbu.type
    type Yerevan = Yerevan.type
    type Omsk = Omsk.type
    type Bahrain = Bahrain.type
    type Tehran = Tehran.type
    type KualaLumpur = KualaLumpur.type
    type Samarkand = Samarkand.type
    type Krasnoyarsk = Krasnoyarsk.type
    type Srednekolymsk = Srednekolymsk.type
    type Singapore = Singapore.type
    type Aqtau = Aqtau.type
    type Hebron = Hebron.type
    type Dacca = Dacca.type
    type Harbin = Harbin.type
    type Karachi = Karachi.type
    type Magadan = Magadan.type
    type Kashgar = Kashgar.type
    type Vladivostok = Vladivostok.type
    type Thimphu = Thimphu.type
    type Amman = Amman.type
    type Tbilisi = Tbilisi.type
    type Jerusalem = Jerusalem.type
    type Brunei = Brunei.type
    type Sakhalin = Sakhalin.type
    type UlanBator = UlanBator.type
    type Novosibirsk = Novosibirsk.type
    type UjungPandang = UjungPandang.type
    type Aden = Aden.type
    type Kolkata = Kolkata.type
    type Baghdad = Baghdad.type
    type Dhaka = Dhaka.type
    type Novokuznetsk = Novokuznetsk.type
    type Ashkhabad = Ashkhabad.type
    type Almaty = Almaty.type
    type Aqtobe = Aqtobe.type
    type Chita = Chita.type
    type Khandyga = Khandyga.type
    type Choibalsan = Choibalsan.type
    type Jayapura = Jayapura.type
    type Nicosia = Nicosia.type
    type Kabul = Kabul.type
    type Kathmandu = Kathmandu.type
    type HoChiMinh = HoChiMinh.type
    type UstNera = UstNera.type
    type Baku = Baku.type
    implicit object Urumqi extends TimeZone(id = "Asia/Urumqi")
    implicit object Damascus extends TimeZone(id = "Asia/Damascus")
    implicit object Ulaanbaatar extends TimeZone(id = "Asia/Ulaanbaatar")
    implicit object Ashgabat extends TimeZone(id = "Asia/Ashgabat")
    implicit object Jakarta extends TimeZone(id = "Asia/Jakarta")
    implicit object Tokyo extends TimeZone(id = "Asia/Tokyo")
    implicit object Muscat extends TimeZone(id = "Asia/Muscat")
    implicit object Hovd extends TimeZone(id = "Asia/Hovd")
    implicit object Rangoon extends TimeZone(id = "Asia/Rangoon")
    implicit object Qyzylorda extends TimeZone(id = "Asia/Qyzylorda")
    implicit object Macau extends TimeZone(id = "Asia/Macau")
    implicit object Pyongyang extends TimeZone(id = "Asia/Pyongyang")
    implicit object Anadyr extends TimeZone(id = "Asia/Anadyr")
    implicit object Chungking extends TimeZone(id = "Asia/Chungking")
    implicit object Yekaterinburg extends TimeZone(id = "Asia/Yekaterinburg")
    implicit object Qatar extends TimeZone(id = "Asia/Qatar")
    implicit object HongKong extends TimeZone(id = "Asia/Hong_Kong")
    implicit object Kamchatka extends TimeZone(id = "Asia/Kamchatka")
    implicit object Bishkek extends TimeZone(id = "Asia/Bishkek")
    implicit object Calcutta extends TimeZone(id = "Asia/Calcutta")
    implicit object Beirut extends TimeZone(id = "Asia/Beirut")
    implicit object Makassar extends TimeZone(id = "Asia/Makassar")
    implicit object Dushanbe extends TimeZone(id = "Asia/Dushanbe")
    implicit object Vientiane extends TimeZone(id = "Asia/Vientiane")
    implicit object Istanbul extends TimeZone(id = "Asia/Istanbul")
    implicit object Taipei extends TimeZone(id = "Asia/Taipei")
    implicit object Colombo extends TimeZone(id = "Asia/Colombo")
    implicit object Shanghai extends TimeZone(id = "Asia/Shanghai")
    implicit object Saigon extends TimeZone(id = "Asia/Saigon")
    implicit object Chongqing extends TimeZone(id = "Asia/Chongqing")
    implicit object Macao extends TimeZone(id = "Asia/Macao")
    implicit object Bangkok extends TimeZone(id = "Asia/Bangkok")
    implicit object Oral extends TimeZone(id = "Asia/Oral")
    implicit object Kuwait extends TimeZone(id = "Asia/Kuwait")
    implicit object Dubai extends TimeZone(id = "Asia/Dubai")
    implicit object Katmandu extends TimeZone(id = "Asia/Katmandu")
    implicit object Irkutsk extends TimeZone(id = "Asia/Irkutsk")
    implicit object Seoul extends TimeZone(id = "Asia/Seoul")
    implicit object Pontianak extends TimeZone(id = "Asia/Pontianak")
    implicit object Kuching extends TimeZone(id = "Asia/Kuching")
    implicit object Tashkent extends TimeZone(id = "Asia/Tashkent")
    implicit object Riyadh extends TimeZone(id = "Asia/Riyadh")
    implicit object Dili extends TimeZone(id = "Asia/Dili")
    implicit object TelAviv extends TimeZone(id = "Asia/Tel_Aviv")
    implicit object PhnomPenh extends TimeZone(id = "Asia/Phnom_Penh")
    implicit object Yakutsk extends TimeZone(id = "Asia/Yakutsk")
    implicit object Gaza extends TimeZone(id = "Asia/Gaza")
    implicit object Manila extends TimeZone(id = "Asia/Manila")
    implicit object Thimbu extends TimeZone(id = "Asia/Thimbu")
    implicit object Yerevan extends TimeZone(id = "Asia/Yerevan")
    implicit object Omsk extends TimeZone(id = "Asia/Omsk")
    implicit object Bahrain extends TimeZone(id = "Asia/Bahrain")
    implicit object Tehran extends TimeZone(id = "Asia/Tehran")
    implicit object KualaLumpur extends TimeZone(id = "Asia/Kuala_Lumpur")
    implicit object Samarkand extends TimeZone(id = "Asia/Samarkand")
    implicit object Krasnoyarsk extends TimeZone(id = "Asia/Krasnoyarsk")
    implicit object Srednekolymsk extends TimeZone(id = "Asia/Srednekolymsk")
    implicit object Singapore extends TimeZone(id = "Asia/Singapore")
    implicit object Aqtau extends TimeZone(id = "Asia/Aqtau")
    implicit object Hebron extends TimeZone(id = "Asia/Hebron")
    implicit object Dacca extends TimeZone(id = "Asia/Dacca")
    implicit object Harbin extends TimeZone(id = "Asia/Harbin")
    implicit object Karachi extends TimeZone(id = "Asia/Karachi")
    implicit object Magadan extends TimeZone(id = "Asia/Magadan")
    implicit object Kashgar extends TimeZone(id = "Asia/Kashgar")
    implicit object Vladivostok extends TimeZone(id = "Asia/Vladivostok")
    implicit object Thimphu extends TimeZone(id = "Asia/Thimphu")
    implicit object Amman extends TimeZone(id = "Asia/Amman")
    implicit object Tbilisi extends TimeZone(id = "Asia/Tbilisi")
    implicit object Jerusalem extends TimeZone(id = "Asia/Jerusalem")
    implicit object Brunei extends TimeZone(id = "Asia/Brunei")
    implicit object Sakhalin extends TimeZone(id = "Asia/Sakhalin")
    implicit object UlanBator extends TimeZone(id = "Asia/Ulan_Bator")
    implicit object Novosibirsk extends TimeZone(id = "Asia/Novosibirsk")
    implicit object UjungPandang extends TimeZone(id = "Asia/Ujung_Pandang")
    implicit object Aden extends TimeZone(id = "Asia/Aden")
    implicit object Kolkata extends TimeZone(id = "Asia/Kolkata")
    implicit object Baghdad extends TimeZone(id = "Asia/Baghdad")
    implicit object Dhaka extends TimeZone(id = "Asia/Dhaka")
    implicit object Novokuznetsk extends TimeZone(id = "Asia/Novokuznetsk")
    implicit object Ashkhabad extends TimeZone(id = "Asia/Ashkhabad")
    implicit object Almaty extends TimeZone(id = "Asia/Almaty")
    implicit object Aqtobe extends TimeZone(id = "Asia/Aqtobe")
    implicit object Chita extends TimeZone(id = "Asia/Chita")
    implicit object Khandyga extends TimeZone(id = "Asia/Khandyga")
    implicit object Choibalsan extends TimeZone(id = "Asia/Choibalsan")
    implicit object Jayapura extends TimeZone(id = "Asia/Jayapura")
    implicit object Nicosia extends TimeZone(id = "Asia/Nicosia")
    implicit object Kabul extends TimeZone(id = "Asia/Kabul")
    implicit object Kathmandu extends TimeZone(id = "Asia/Kathmandu")
    implicit object HoChiMinh extends TimeZone(id = "Asia/Ho_Chi_Minh")
    implicit object UstNera extends TimeZone(id = "Asia/Ust-Nera")
    implicit object Baku extends TimeZone(id = "Asia/Baku")
  }
  object Mexico {
    type BajaSur = BajaSur.type
    type BajaNorte = BajaNorte.type
    type General = General.type
    implicit object BajaSur extends TimeZone(id = "Mexico/BajaSur")
    implicit object BajaNorte extends TimeZone(id = "Mexico/BajaNorte")
    implicit object General extends TimeZone(id = "Mexico/General")
  }
  object US {
    type Alaska = Alaska.type
    type Samoa = Samoa.type
    type Hawaii = Hawaii.type
    type IndianaStarke = IndianaStarke.type
    type Eastern = Eastern.type
    type Mountain = Mountain.type
    type Central = Central.type
    type Arizona = Arizona.type
    type Aleutian = Aleutian.type
    type EastIndiana = EastIndiana.type
    type Pacific = Pacific.type
    type PacificNew = PacificNew.type
    type Michigan = Michigan.type
    implicit object Alaska extends TimeZone(id = "US/Alaska")
    implicit object Samoa extends TimeZone(id = "US/Samoa")
    implicit object Hawaii extends TimeZone(id = "US/Hawaii")
    implicit object IndianaStarke extends TimeZone(id = "US/Indiana-Starke")
    implicit object Eastern extends TimeZone(id = "US/Eastern")
    implicit object Mountain extends TimeZone(id = "US/Mountain")
    implicit object Central extends TimeZone(id = "US/Central")
    implicit object Arizona extends TimeZone(id = "US/Arizona")
    implicit object Aleutian extends TimeZone(id = "US/Aleutian")
    implicit object EastIndiana extends TimeZone(id = "US/East-Indiana")
    implicit object Pacific extends TimeZone(id = "US/Pacific")
    implicit object PacificNew extends TimeZone(id = "US/Pacific-New")
    implicit object Michigan extends TimeZone(id = "US/Michigan")
  }
  object America {
    type Asuncion = Asuncion.type
    type CoralHarbour = CoralHarbour.type
    type Montreal = Montreal.type
    type Denver = Denver.type
    type StJohns = StJohns.type
    type Godthab = Godthab.type
    type Vancouver = Vancouver.type
    type Santiago = Santiago.type
    type Monterrey = Monterrey.type
    type Curacao = Curacao.type
    type Yakutat = Yakutat.type
    type Anchorage = Anchorage.type
    type Managua = Managua.type
    type Dominica = Dominica.type
    type PortoVelho = PortoVelho.type
    type Martinique = Martinique.type
    type Yellowknife = Yellowknife.type
    type Indianapolis = Indianapolis.type
    type Cancun = Cancun.type
    type Anguilla = Anguilla.type
    type Atikokan = Atikokan.type
    type Halifax = Halifax.type
    type Nassau = Nassau.type
    type Matamoros = Matamoros.type
    type Chicago = Chicago.type
    type LosAngeles = LosAngeles.type
    type Rosario = Rosario.type
    type Bahia = Bahia.type
    type Guatemala = Guatemala.type
    type Guadeloupe = Guadeloupe.type
    type PortoAcre = PortoAcre.type
    type Tijuana = Tijuana.type
    type Inuvik = Inuvik.type
    type Whitehorse = Whitehorse.type
    type PortAuPrince = PortAuPrince.type
    type Kralendijk = Kralendijk.type
    type KnoxIn = KnoxIn.type
    type Atka = Atka.type
    type Ojinaga = Ojinaga.type
    type Cordoba = Cordoba.type
    type Panama = Panama.type
    type Antigua = Antigua.type
    type NewYork = NewYork.type
    type StBarthelemy = StBarthelemy.type
    type Ensenada = Ensenada.type
    type Montevideo = Montevideo.type
    type Louisville = Louisville.type
    type Caracas = Caracas.type
    type Catamarca = Catamarca.type
    type Hermosillo = Hermosillo.type
    type NorthDakota = NorthDakota.type
    type NorthDakotaCenter = NorthDakotaCenter.type
    type NorthDakotaBeulah = NorthDakotaBeulah.type
    type NorthDakotaNewSalem = NorthDakotaNewSalem.type
    type Adak = Adak.type
    type ElSalvador = ElSalvador.type
    type Cuiaba = Cuiaba.type
    type GooseBay = GooseBay.type
    type Thule = Thule.type
    type Moncton = Moncton.type
    type DawsonCreek = DawsonCreek.type
    type Recife = Recife.type
    type Fortaleza = Fortaleza.type
    type Pangnirtung = Pangnirtung.type
    type Regina = Regina.type
    type Lima = Lima.type
    type Virgin = Virgin.type
    type RioBranco = RioBranco.type
    type CambridgeBay = CambridgeBay.type
    type Maceio = Maceio.type
    type Creston = Creston.type
    type StVincent = StVincent.type
    type PuertoRico = PuertoRico.type
    type Boise = Boise.type
    type Nipigon = Nipigon.type
    type SaoPaulo = SaoPaulo.type
    type PortOfSpain = PortOfSpain.type
    type Menominee = Menominee.type
    type Indiana = Indiana.type
    type IndianaTellCity = IndianaTellCity.type
    type IndianaIndianapolis = IndianaIndianapolis.type
    type IndianaWinamac = IndianaWinamac.type
    type IndianaVincennes = IndianaVincennes.type
    type IndianaKnox = IndianaKnox.type
    type IndianaPetersburg = IndianaPetersburg.type
    type IndianaVevay = IndianaVevay.type
    type IndianaMarengo = IndianaMarengo.type
    type Miquelon = Miquelon.type
    type Danmarkshavn = Danmarkshavn.type
    type BlancSablon = BlancSablon.type
    type Metlakatla = Metlakatla.type
    type RainyRiver = RainyRiver.type
    type Phoenix = Phoenix.type
    type Juneau = Juneau.type
    type CostaRica = CostaRica.type
    type Bogota = Bogota.type
    type Barbados = Barbados.type
    type Noronha = Noronha.type
    type Chihuahua = Chihuahua.type
    type LowerPrinces = LowerPrinces.type
    type Winnipeg = Winnipeg.type
    type Scoresbysund = Scoresbysund.type
    type Grenada = Grenada.type
    type Toronto = Toronto.type
    type Mendoza = Mendoza.type
    type Paramaribo = Paramaribo.type
    type SantoDomingo = SantoDomingo.type
    type Shiprock = Shiprock.type
    type MexicoCity = MexicoCity.type
    type SantaIsabel = SantaIsabel.type
    type ThunderBay = ThunderBay.type
    type RankinInlet = RankinInlet.type
    type Santarem = Santarem.type
    type Havana = Havana.type
    type Edmonton = Edmonton.type
    type CampoGrande = CampoGrande.type
    type Belem = Belem.type
    type SwiftCurrent = SwiftCurrent.type
    type Montserrat = Montserrat.type
    type Dawson = Dawson.type
    type Tortola = Tortola.type
    type Marigot = Marigot.type
    type Resolute = Resolute.type
    type FortWayne = FortWayne.type
    type Jujuy = Jujuy.type
    type BuenosAires = BuenosAires.type
    type Sitka = Sitka.type
    type Merida = Merida.type
    type Eirunepe = Eirunepe.type
    type StThomas = StThomas.type
    type Nome = Nome.type
    type Tegucigalpa = Tegucigalpa.type
    type BahiaBanderas = BahiaBanderas.type
    type Detroit = Detroit.type
    type Cayenne = Cayenne.type
    type BoaVista = BoaVista.type
    type Araguaina = Araguaina.type
    type Iqaluit = Iqaluit.type
    type LaPaz = LaPaz.type
    type Guyana = Guyana.type
    type Jamaica = Jamaica.type
    type Belize = Belize.type
    type GlaceBay = GlaceBay.type
    type Cayman = Cayman.type
    type StLucia = StLucia.type
    type KentuckyLouisville = KentuckyLouisville.type
    type KentuckyMonticello = KentuckyMonticello.type
    type Mazatlan = Mazatlan.type
    type GrandTurk = GrandTurk.type
    type Aruba = Aruba.type
    type Manaus = Manaus.type
    type Argentina = Argentina.type
    type ArgentinaComodRivadavia = ArgentinaComodRivadavia.type
    type ArgentinaLaRioja = ArgentinaLaRioja.type
    type ArgentinaRioGallegos = ArgentinaRioGallegos.type
    type ArgentinaUshuaia = ArgentinaUshuaia.type
    type ArgentinaCordoba = ArgentinaCordoba.type
    type ArgentinaSanLuis = ArgentinaSanLuis.type
    type ArgentinaCatamarca = ArgentinaCatamarca.type
    type ArgentinaSanJuan = ArgentinaSanJuan.type
    type ArgentinaTucuman = ArgentinaTucuman.type
    type ArgentinaMendoza = ArgentinaMendoza.type
    type ArgentinaJujuy = ArgentinaJujuy.type
    type ArgentinaSalta = ArgentinaSalta.type
    type ArgentinaBuenosAires = ArgentinaBuenosAires.type
    type Guayaquil = Guayaquil.type
    type StKitts = StKitts.type
    implicit object Asuncion extends TimeZone(id = "America/Asuncion")
    implicit object CoralHarbour extends TimeZone(id = "America/Coral_Harbour")
    implicit object Montreal extends TimeZone(id = "America/Montreal")
    implicit object Denver extends TimeZone(id = "America/Denver")
    implicit object StJohns extends TimeZone(id = "America/St_Johns")
    implicit object Godthab extends TimeZone(id = "America/Godthab")
    implicit object Vancouver extends TimeZone(id = "America/Vancouver")
    implicit object Santiago extends TimeZone(id = "America/Santiago")
    implicit object Monterrey extends TimeZone(id = "America/Monterrey")
    implicit object Curacao extends TimeZone(id = "America/Curacao")
    implicit object Yakutat extends TimeZone(id = "America/Yakutat")
    implicit object Anchorage extends TimeZone(id = "America/Anchorage")
    implicit object Managua extends TimeZone(id = "America/Managua")
    implicit object Dominica extends TimeZone(id = "America/Dominica")
    implicit object PortoVelho extends TimeZone(id = "America/Porto_Velho")
    implicit object Martinique extends TimeZone(id = "America/Martinique")
    implicit object Yellowknife extends TimeZone(id = "America/Yellowknife")
    implicit object Indianapolis extends TimeZone(id = "America/Indianapolis")
    implicit object Cancun extends TimeZone(id = "America/Cancun")
    implicit object Anguilla extends TimeZone(id = "America/Anguilla")
    implicit object Atikokan extends TimeZone(id = "America/Atikokan")
    implicit object Halifax extends TimeZone(id = "America/Halifax")
    implicit object Nassau extends TimeZone(id = "America/Nassau")
    implicit object Matamoros extends TimeZone(id = "America/Matamoros")
    implicit object Chicago extends TimeZone(id = "America/Chicago")
    implicit object LosAngeles extends TimeZone(id = "America/Los_Angeles")
    implicit object Rosario extends TimeZone(id = "America/Rosario")
    implicit object Bahia extends TimeZone(id = "America/Bahia")
    implicit object Guatemala extends TimeZone(id = "America/Guatemala")
    implicit object Guadeloupe extends TimeZone(id = "America/Guadeloupe")
    implicit object PortoAcre extends TimeZone(id = "America/Porto_Acre")
    implicit object Tijuana extends TimeZone(id = "America/Tijuana")
    implicit object Inuvik extends TimeZone(id = "America/Inuvik")
    implicit object Whitehorse extends TimeZone(id = "America/Whitehorse")
    implicit object PortAuPrince extends TimeZone(id = "America/Port-au-Prince")
    implicit object Kralendijk extends TimeZone(id = "America/Kralendijk")
    implicit object KnoxIn extends TimeZone(id = "America/Knox_IN")
    implicit object Atka extends TimeZone(id = "America/Atka")
    implicit object Ojinaga extends TimeZone(id = "America/Ojinaga")
    implicit object Cordoba extends TimeZone(id = "America/Cordoba")
    implicit object Panama extends TimeZone(id = "America/Panama")
    implicit object Antigua extends TimeZone(id = "America/Antigua")
    implicit object NewYork extends TimeZone(id = "America/New_York")
    implicit object StBarthelemy extends TimeZone(id = "America/St_Barthelemy")
    implicit object Ensenada extends TimeZone(id = "America/Ensenada")
    implicit object Montevideo extends TimeZone(id = "America/Montevideo")
    implicit object Louisville extends TimeZone(id = "America/Louisville")
    implicit object Caracas extends TimeZone(id = "America/Caracas")
    implicit object Catamarca extends TimeZone(id = "America/Catamarca")
    implicit object Hermosillo extends TimeZone(id = "America/Hermosillo")
    implicit object NorthDakota extends TimeZone(id = "America/North_Dakota")
    implicit object NorthDakotaCenter extends TimeZone(id = "America/North_Dakota/Center")
    implicit object NorthDakotaBeulah extends TimeZone(id = "America/North_Dakota/Beulah")
    implicit object NorthDakotaNewSalem extends TimeZone(id = "America/North_Dakota/New_Salem")
    implicit object Adak extends TimeZone(id = "America/Adak")
    implicit object ElSalvador extends TimeZone(id = "America/El_Salvador")
    implicit object Cuiaba extends TimeZone(id = "America/Cuiaba")
    implicit object GooseBay extends TimeZone(id = "America/Goose_Bay")
    implicit object Thule extends TimeZone(id = "America/Thule")
    implicit object Moncton extends TimeZone(id = "America/Moncton")
    implicit object DawsonCreek extends TimeZone(id = "America/Dawson_Creek")
    implicit object Recife extends TimeZone(id = "America/Recife")
    implicit object Fortaleza extends TimeZone(id = "America/Fortaleza")
    implicit object Pangnirtung extends TimeZone(id = "America/Pangnirtung")
    implicit object Regina extends TimeZone(id = "America/Regina")
    implicit object Lima extends TimeZone(id = "America/Lima")
    implicit object Virgin extends TimeZone(id = "America/Virgin")
    implicit object RioBranco extends TimeZone(id = "America/Rio_Branco")
    implicit object CambridgeBay extends TimeZone(id = "America/Cambridge_Bay")
    implicit object Maceio extends TimeZone(id = "America/Maceio")
    implicit object Creston extends TimeZone(id = "America/Creston")
    implicit object StVincent extends TimeZone(id = "America/St_Vincent")
    implicit object PuertoRico extends TimeZone(id = "America/Puerto_Rico")
    implicit object Boise extends TimeZone(id = "America/Boise")
    implicit object Nipigon extends TimeZone(id = "America/Nipigon")
    implicit object SaoPaulo extends TimeZone(id = "America/Sao_Paulo")
    implicit object PortOfSpain extends TimeZone(id = "America/Port_of_Spain")
    implicit object Menominee extends TimeZone(id = "America/Menominee")
    implicit object Indiana extends TimeZone(id = "America/Indiana")
    implicit object IndianaTellCity extends TimeZone(id = "America/Indiana/Tell_City")
    implicit object IndianaIndianapolis extends TimeZone(id = "America/Indiana/Indianapolis")
    implicit object IndianaWinamac extends TimeZone(id = "America/Indiana/Winamac")
    implicit object IndianaVincennes extends TimeZone(id = "America/Indiana/Vincennes")
    implicit object IndianaKnox extends TimeZone(id = "America/Indiana/Knox")
    implicit object IndianaPetersburg extends TimeZone(id = "America/Indiana/Petersburg")
    implicit object IndianaVevay extends TimeZone(id = "America/Indiana/Vevay")
    implicit object IndianaMarengo extends TimeZone(id = "America/Indiana/Marengo")
    implicit object Miquelon extends TimeZone(id = "America/Miquelon")
    implicit object Danmarkshavn extends TimeZone(id = "America/Danmarkshavn")
    implicit object BlancSablon extends TimeZone(id = "America/Blanc-Sablon")
    implicit object Metlakatla extends TimeZone(id = "America/Metlakatla")
    implicit object RainyRiver extends TimeZone(id = "America/Rainy_River")
    implicit object Phoenix extends TimeZone(id = "America/Phoenix")
    implicit object Juneau extends TimeZone(id = "America/Juneau")
    implicit object CostaRica extends TimeZone(id = "America/Costa_Rica")
    implicit object Bogota extends TimeZone(id = "America/Bogota")
    implicit object Barbados extends TimeZone(id = "America/Barbados")
    implicit object Noronha extends TimeZone(id = "America/Noronha")
    implicit object Chihuahua extends TimeZone(id = "America/Chihuahua")
    implicit object LowerPrinces extends TimeZone(id = "America/Lower_Princes")
    implicit object Winnipeg extends TimeZone(id = "America/Winnipeg")
    implicit object Scoresbysund extends TimeZone(id = "America/Scoresbysund")
    implicit object Grenada extends TimeZone(id = "America/Grenada")
    implicit object Toronto extends TimeZone(id = "America/Toronto")
    implicit object Mendoza extends TimeZone(id = "America/Mendoza")
    implicit object Paramaribo extends TimeZone(id = "America/Paramaribo")
    implicit object SantoDomingo extends TimeZone(id = "America/Santo_Domingo")
    implicit object Shiprock extends TimeZone(id = "America/Shiprock")
    implicit object MexicoCity extends TimeZone(id = "America/Mexico_City")
    implicit object SantaIsabel extends TimeZone(id = "America/Santa_Isabel")
    implicit object ThunderBay extends TimeZone(id = "America/Thunder_Bay")
    implicit object RankinInlet extends TimeZone(id = "America/Rankin_Inlet")
    implicit object Santarem extends TimeZone(id = "America/Santarem")
    implicit object Havana extends TimeZone(id = "America/Havana")
    implicit object Edmonton extends TimeZone(id = "America/Edmonton")
    implicit object CampoGrande extends TimeZone(id = "America/Campo_Grande")
    implicit object Belem extends TimeZone(id = "America/Belem")
    implicit object SwiftCurrent extends TimeZone(id = "America/Swift_Current")
    implicit object Montserrat extends TimeZone(id = "America/Montserrat")
    implicit object Dawson extends TimeZone(id = "America/Dawson")
    implicit object Tortola extends TimeZone(id = "America/Tortola")
    implicit object Marigot extends TimeZone(id = "America/Marigot")
    implicit object Resolute extends TimeZone(id = "America/Resolute")
    implicit object FortWayne extends TimeZone(id = "America/Fort_Wayne")
    implicit object Jujuy extends TimeZone(id = "America/Jujuy")
    implicit object BuenosAires extends TimeZone(id = "America/Buenos_Aires")
    implicit object Sitka extends TimeZone(id = "America/Sitka")
    implicit object Merida extends TimeZone(id = "America/Merida")
    implicit object Eirunepe extends TimeZone(id = "America/Eirunepe")
    implicit object StThomas extends TimeZone(id = "America/St_Thomas")
    implicit object Nome extends TimeZone(id = "America/Nome")
    implicit object Tegucigalpa extends TimeZone(id = "America/Tegucigalpa")
    implicit object BahiaBanderas extends TimeZone(id = "America/Bahia_Banderas")
    implicit object Detroit extends TimeZone(id = "America/Detroit")
    implicit object Cayenne extends TimeZone(id = "America/Cayenne")
    implicit object BoaVista extends TimeZone(id = "America/Boa_Vista")
    implicit object Araguaina extends TimeZone(id = "America/Araguaina")
    implicit object Iqaluit extends TimeZone(id = "America/Iqaluit")
    implicit object LaPaz extends TimeZone(id = "America/La_Paz")
    implicit object Guyana extends TimeZone(id = "America/Guyana")
    implicit object Jamaica extends TimeZone(id = "America/Jamaica")
    implicit object Belize extends TimeZone(id = "America/Belize")
    implicit object GlaceBay extends TimeZone(id = "America/Glace_Bay")
    implicit object Cayman extends TimeZone(id = "America/Cayman")
    implicit object StLucia extends TimeZone(id = "America/St_Lucia")
    implicit object KentuckyLouisville extends TimeZone(id = "America/Kentucky/Louisville")
    implicit object KentuckyMonticello extends TimeZone(id = "America/Kentucky/Monticello")
    implicit object Mazatlan extends TimeZone(id = "America/Mazatlan")
    implicit object GrandTurk extends TimeZone(id = "America/Grand_Turk")
    implicit object Aruba extends TimeZone(id = "America/Aruba")
    implicit object Manaus extends TimeZone(id = "America/Manaus")
    implicit object Argentina extends TimeZone(id = "America/Argentina")
    implicit object ArgentinaComodRivadavia extends TimeZone(id = "America/Argentina/ComodRivadavia")
    implicit object ArgentinaLaRioja extends TimeZone(id = "America/Argentina/La_Rioja")
    implicit object ArgentinaRioGallegos extends TimeZone(id = "America/Argentina/Rio_Gallegos")
    implicit object ArgentinaUshuaia extends TimeZone(id = "America/Argentina/Ushuaia")
    implicit object ArgentinaCordoba extends TimeZone(id = "America/Argentina/Cordoba")
    implicit object ArgentinaSanLuis extends TimeZone(id = "America/Argentina/San_Luis")
    implicit object ArgentinaCatamarca extends TimeZone(id = "America/Argentina/Catamarca")
    implicit object ArgentinaSanJuan extends TimeZone(id = "America/Argentina/San_Juan")
    implicit object ArgentinaTucuman extends TimeZone(id = "America/Argentina/Tucuman")
    implicit object ArgentinaMendoza extends TimeZone(id = "America/Argentina/Mendoza")
    implicit object ArgentinaJujuy extends TimeZone(id = "America/Argentina/Jujuy")
    implicit object ArgentinaSalta extends TimeZone(id = "America/Argentina/Salta")
    implicit object ArgentinaBuenosAires extends TimeZone(id = "America/Argentina/Buenos_Aires")
    implicit object Guayaquil extends TimeZone(id = "America/Guayaquil")
    implicit object StKitts extends TimeZone(id = "America/St_Kitts")
  }
  object Africa {
    type Windhoek = Windhoek.type
    type DarEsSalaam = DarEsSalaam.type
    type Asmara = Asmara.type
    type Cairo = Cairo.type
    type Juba = Juba.type
    type Timbuktu = Timbuktu.type
    type Dakar = Dakar.type
    type Monrovia = Monrovia.type
    type Blantyre = Blantyre.type
    type Lagos = Lagos.type
    type Banjul = Banjul.type
    type Abidjan = Abidjan.type
    type Asmera = Asmera.type
    type Kigali = Kigali.type
    type Gaborone = Gaborone.type
    type Malabo = Malabo.type
    type Nouakchott = Nouakchott.type
    type Lubumbashi = Lubumbashi.type
    type Khartoum = Khartoum.type
    type Maseru = Maseru.type
    type Kinshasa = Kinshasa.type
    type Johannesburg = Johannesburg.type
    type Luanda = Luanda.type
    type Bamako = Bamako.type
    type Lome = Lome.type
    type Lusaka = Lusaka.type
    type PortoNovo = PortoNovo.type
    type Kampala = Kampala.type
    type Brazzaville = Brazzaville.type
    type Djibouti = Djibouti.type
    type Nairobi = Nairobi.type
    type Mogadishu = Mogadishu.type
    type ElAaiun = ElAaiun.type
    type Maputo = Maputo.type
    type Bissau = Bissau.type
    type AddisAbaba = AddisAbaba.type
    type Harare = Harare.type
    type Libreville = Libreville.type
    type Freetown = Freetown.type
    type Niamey = Niamey.type
    type Conakry = Conakry.type
    type Douala = Douala.type
    type Ceuta = Ceuta.type
    type Ndjamena = Ndjamena.type
    type Bujumbura = Bujumbura.type
    type Bangui = Bangui.type
    type Algiers = Algiers.type
    type Ouagadougou = Ouagadougou.type
    type Casablanca = Casablanca.type
    type Tripoli = Tripoli.type
    type SaoTome = SaoTome.type
    type Mbabane = Mbabane.type
    type Accra = Accra.type
    type Tunis = Tunis.type
    implicit object Windhoek extends TimeZone(id = "Africa/Windhoek")
    implicit object DarEsSalaam extends TimeZone(id = "Africa/Dar_es_Salaam")
    implicit object Asmara extends TimeZone(id = "Africa/Asmara")
    implicit object Cairo extends TimeZone(id = "Africa/Cairo")
    implicit object Juba extends TimeZone(id = "Africa/Juba")
    implicit object Timbuktu extends TimeZone(id = "Africa/Timbuktu")
    implicit object Dakar extends TimeZone(id = "Africa/Dakar")
    implicit object Monrovia extends TimeZone(id = "Africa/Monrovia")
    implicit object Blantyre extends TimeZone(id = "Africa/Blantyre")
    implicit object Lagos extends TimeZone(id = "Africa/Lagos")
    implicit object Banjul extends TimeZone(id = "Africa/Banjul")
    implicit object Abidjan extends TimeZone(id = "Africa/Abidjan")
    implicit object Asmera extends TimeZone(id = "Africa/Asmera")
    implicit object Kigali extends TimeZone(id = "Africa/Kigali")
    implicit object Gaborone extends TimeZone(id = "Africa/Gaborone")
    implicit object Malabo extends TimeZone(id = "Africa/Malabo")
    implicit object Nouakchott extends TimeZone(id = "Africa/Nouakchott")
    implicit object Lubumbashi extends TimeZone(id = "Africa/Lubumbashi")
    implicit object Khartoum extends TimeZone(id = "Africa/Khartoum")
    implicit object Maseru extends TimeZone(id = "Africa/Maseru")
    implicit object Kinshasa extends TimeZone(id = "Africa/Kinshasa")
    implicit object Johannesburg extends TimeZone(id = "Africa/Johannesburg")
    implicit object Luanda extends TimeZone(id = "Africa/Luanda")
    implicit object Bamako extends TimeZone(id = "Africa/Bamako")
    implicit object Lome extends TimeZone(id = "Africa/Lome")
    implicit object Lusaka extends TimeZone(id = "Africa/Lusaka")
    implicit object PortoNovo extends TimeZone(id = "Africa/Porto-Novo")
    implicit object Kampala extends TimeZone(id = "Africa/Kampala")
    implicit object Brazzaville extends TimeZone(id = "Africa/Brazzaville")
    implicit object Djibouti extends TimeZone(id = "Africa/Djibouti")
    implicit object Nairobi extends TimeZone(id = "Africa/Nairobi")
    implicit object Mogadishu extends TimeZone(id = "Africa/Mogadishu")
    implicit object ElAaiun extends TimeZone(id = "Africa/El_Aaiun")
    implicit object Maputo extends TimeZone(id = "Africa/Maputo")
    implicit object Bissau extends TimeZone(id = "Africa/Bissau")
    implicit object AddisAbaba extends TimeZone(id = "Africa/Addis_Ababa")
    implicit object Harare extends TimeZone(id = "Africa/Harare")
    implicit object Libreville extends TimeZone(id = "Africa/Libreville")
    implicit object Freetown extends TimeZone(id = "Africa/Freetown")
    implicit object Niamey extends TimeZone(id = "Africa/Niamey")
    implicit object Conakry extends TimeZone(id = "Africa/Conakry")
    implicit object Douala extends TimeZone(id = "Africa/Douala")
    implicit object Ceuta extends TimeZone(id = "Africa/Ceuta")
    implicit object Ndjamena extends TimeZone(id = "Africa/Ndjamena")
    implicit object Bujumbura extends TimeZone(id = "Africa/Bujumbura")
    implicit object Bangui extends TimeZone(id = "Africa/Bangui")
    implicit object Algiers extends TimeZone(id = "Africa/Algiers")
    implicit object Ouagadougou extends TimeZone(id = "Africa/Ouagadougou")
    implicit object Casablanca extends TimeZone(id = "Africa/Casablanca")
    implicit object Tripoli extends TimeZone(id = "Africa/Tripoli")
    implicit object SaoTome extends TimeZone(id = "Africa/Sao_Tome")
    implicit object Mbabane extends TimeZone(id = "Africa/Mbabane")
    implicit object Accra extends TimeZone(id = "Africa/Accra")
    implicit object Tunis extends TimeZone(id = "Africa/Tunis")
  }
  object Atlantic {
    implicit object Faeroe extends TimeZone(id = "Atlantic/Faeroe")
    implicit object Bermuda extends TimeZone(id = "Atlantic/Bermuda")
    implicit object Azores extends TimeZone(id = "Atlantic/Azores")
    implicit object Stanley extends TimeZone(id = "Atlantic/Stanley")
    implicit object StHelena extends TimeZone(id = "Atlantic/St_Helena")
    implicit object Faroe extends TimeZone(id = "Atlantic/Faroe")
    implicit object CapeVerde extends TimeZone(id = "Atlantic/Cape_Verde")
    implicit object SouthGeorgia extends TimeZone(id = "Atlantic/South_Georgia")
    implicit object Madeira extends TimeZone(id = "Atlantic/Madeira")
    implicit object Canary extends TimeZone(id = "Atlantic/Canary")
    implicit object Reykjavik extends TimeZone(id = "Atlantic/Reykjavik")
    implicit object JanMayen extends TimeZone(id = "Atlantic/Jan_Mayen")
  }
  object Pacific {
    type Majuro = Majuro.type
    type Tongatapu = Tongatapu.type
    type Pohnpei = Pohnpei.type
    type Noumea = Noumea.type
    type Kosrae = Kosrae.type
    type Tahiti = Tahiti.type
    type Auckland = Auckland.type
    type Samoa = Samoa.type
    type PortMoresby = PortMoresby.type
    type Galapagos = Galapagos.type
    type Wallis = Wallis.type
    type Fakaofo = Fakaofo.type
    type Palau = Palau.type
    type Pitcairn = Pitcairn.type
    type Midway = Midway.type
    type Yap = Yap.type
    type Gambier = Gambier.type
    type Guam = Guam.type
    type Nauru = Nauru.type
    type Rarotonga = Rarotonga.type
    type Honolulu = Honolulu.type
    type Enderbury = Enderbury.type
    type Guadalcanal = Guadalcanal.type
    type Truk = Truk.type
    type Chatham = Chatham.type
    type Kiritimati = Kiritimati.type
    type Saipan = Saipan.type
    type Funafuti = Funafuti.type
    type Kwajalein = Kwajalein.type
    type Fiji = Fiji.type
    type Johnston = Johnston.type
    type Efate = Efate.type
    type Apia = Apia.type
    type Easter = Easter.type
    type Tarawa = Tarawa.type
    type Ponape = Ponape.type
    type Marquesas = Marquesas.type
    type Chuuk = Chuuk.type
    type Bougainville = Bougainville.type
    type PagoPago = PagoPago.type
    type Norfolk = Norfolk.type
    type Niue = Niue.type
    type Wake = Wake.type
    implicit object Majuro extends TimeZone(id = "Pacific/Majuro")
    implicit object Tongatapu extends TimeZone(id = "Pacific/Tongatapu")
    implicit object Pohnpei extends TimeZone(id = "Pacific/Pohnpei")
    implicit object Noumea extends TimeZone(id = "Pacific/Noumea")
    implicit object Kosrae extends TimeZone(id = "Pacific/Kosrae")
    implicit object Tahiti extends TimeZone(id = "Pacific/Tahiti")
    implicit object Auckland extends TimeZone(id = "Pacific/Auckland")
    implicit object Samoa extends TimeZone(id = "Pacific/Samoa")
    implicit object PortMoresby extends TimeZone(id = "Pacific/Port_Moresby")
    implicit object Galapagos extends TimeZone(id = "Pacific/Galapagos")
    implicit object Wallis extends TimeZone(id = "Pacific/Wallis")
    implicit object Fakaofo extends TimeZone(id = "Pacific/Fakaofo")
    implicit object Palau extends TimeZone(id = "Pacific/Palau")
    implicit object Pitcairn extends TimeZone(id = "Pacific/Pitcairn")
    implicit object Midway extends TimeZone(id = "Pacific/Midway")
    implicit object Yap extends TimeZone(id = "Pacific/Yap")
    implicit object Gambier extends TimeZone(id = "Pacific/Gambier")
    implicit object Guam extends TimeZone(id = "Pacific/Guam")
    implicit object Nauru extends TimeZone(id = "Pacific/Nauru")
    implicit object Rarotonga extends TimeZone(id = "Pacific/Rarotonga")
    implicit object Honolulu extends TimeZone(id = "Pacific/Honolulu")
    implicit object Enderbury extends TimeZone(id = "Pacific/Enderbury")
    implicit object Guadalcanal extends TimeZone(id = "Pacific/Guadalcanal")
    implicit object Truk extends TimeZone(id = "Pacific/Truk")
    implicit object Chatham extends TimeZone(id = "Pacific/Chatham")
    implicit object Kiritimati extends TimeZone(id = "Pacific/Kiritimati")
    implicit object Saipan extends TimeZone(id = "Pacific/Saipan")
    implicit object Funafuti extends TimeZone(id = "Pacific/Funafuti")
    implicit object Kwajalein extends TimeZone(id = "Pacific/Kwajalein")
    implicit object Fiji extends TimeZone(id = "Pacific/Fiji")
    implicit object Johnston extends TimeZone(id = "Pacific/Johnston")
    implicit object Efate extends TimeZone(id = "Pacific/Efate")
    implicit object Apia extends TimeZone(id = "Pacific/Apia")
    implicit object Easter extends TimeZone(id = "Pacific/Easter")
    implicit object Tarawa extends TimeZone(id = "Pacific/Tarawa")
    implicit object Ponape extends TimeZone(id = "Pacific/Ponape")
    implicit object Marquesas extends TimeZone(id = "Pacific/Marquesas")
    implicit object Chuuk extends TimeZone(id = "Pacific/Chuuk")
    implicit object Bougainville extends TimeZone(id = "Pacific/Bougainville")
    implicit object PagoPago extends TimeZone(id = "Pacific/Pago_Pago")
    implicit object Norfolk extends TimeZone(id = "Pacific/Norfolk")
    implicit object Niue extends TimeZone(id = "Pacific/Niue")
    implicit object Wake extends TimeZone(id = "Pacific/Wake")
  }
  object Antarctica {
    type SouthPole = SouthPole.type
    type DumontDUrville = DumontDUrville.type
    type Macquarie = Macquarie.type
    type Syowa = Syowa.type
    type Davis = Davis.type
    type Rothera = Rothera.type
    type Casey = Casey.type
    type Palmer = Palmer.type
    type Vostok = Vostok.type
    type Mawson = Mawson.type
    type McMurdo = McMurdo.type
    type Troll = Troll.type
    implicit object SouthPole extends TimeZone(id = "Antarctica/South_Pole")
    implicit object DumontDUrville extends TimeZone(id = "Antarctica/DumontDUrville")
    implicit object Macquarie extends TimeZone(id = "Antarctica/Macquarie")
    implicit object Syowa extends TimeZone(id = "Antarctica/Syowa")
    implicit object Davis extends TimeZone(id = "Antarctica/Davis")
    implicit object Rothera extends TimeZone(id = "Antarctica/Rothera")
    implicit object Casey extends TimeZone(id = "Antarctica/Casey")
    implicit object Palmer extends TimeZone(id = "Antarctica/Palmer")
    implicit object Vostok extends TimeZone(id = "Antarctica/Vostok")
    implicit object Mawson extends TimeZone(id = "Antarctica/Mawson")
    implicit object McMurdo extends TimeZone(id = "Antarctica/McMurdo")
    implicit object Troll extends TimeZone(id = "Antarctica/Troll")
  }
  object Indian {
    type Cocos = Cocos.type
    type Maldives = Maldives.type
    type Mayotte = Mayotte.type
    type Christmas = Christmas.type
    type Mauritius = Mauritius.type
    type Kerguelen = Kerguelen.type
    type Chagos = Chagos.type
    type Antananarivo = Antananarivo.type
    type Reunion = Reunion.type
    type Comoro = Comoro.type
    type Mahe = Mahe.type
    implicit object Cocos extends TimeZone(id = "Indian/Cocos")
    implicit object Maldives extends TimeZone(id = "Indian/Maldives")
    implicit object Mayotte extends TimeZone(id = "Indian/Mayotte")
    implicit object Christmas extends TimeZone(id = "Indian/Christmas")
    implicit object Mauritius extends TimeZone(id = "Indian/Mauritius")
    implicit object Kerguelen extends TimeZone(id = "Indian/Kerguelen")
    implicit object Chagos extends TimeZone(id = "Indian/Chagos")
    implicit object Antananarivo extends TimeZone(id = "Indian/Antananarivo")
    implicit object Reunion extends TimeZone(id = "Indian/Reunion")
    implicit object Comoro extends TimeZone(id = "Indian/Comoro")
    implicit object Mahe extends TimeZone(id = "Indian/Mahe")
  }
  object Canada {
    type Eastern = Eastern.type
    type Yukon = Yukon.type
    type Mountain = Mountain.type
    type Central = Central.type
    type EastSaskatchewan = EastSaskatchewan.type
    type Atlantic = Atlantic.type
    type Newfoundland = Newfoundland.type
    type Saskatchewan = Saskatchewan.type
    type Pacific = Pacific.type
    implicit object Eastern extends TimeZone(id = "Canada/Eastern")
    implicit object Yukon extends TimeZone(id = "Canada/Yukon")
    implicit object Mountain extends TimeZone(id = "Canada/Mountain")
    implicit object Central extends TimeZone(id = "Canada/Central")
    implicit object EastSaskatchewan extends TimeZone(id = "Canada/East-Saskatchewan")
    implicit object Atlantic extends TimeZone(id = "Canada/Atlantic")
    implicit object Newfoundland extends TimeZone(id = "Canada/Newfoundland")
    implicit object Saskatchewan extends TimeZone(id = "Canada/Saskatchewan")
    implicit object Pacific extends TimeZone(id = "Canada/Pacific")
  }
  object Brazil {
    type DeNoronha = DeNoronha.type
    type West = West.type
    type East = East.type
    type Acre = Acre.type
    implicit object DeNoronha extends TimeZone(id = "Brazil/DeNoronha")
    implicit object West extends TimeZone(id = "Brazil/West")
    implicit object East extends TimeZone(id = "Brazil/East")
    implicit object Acre extends TimeZone(id = "Brazil/Acre")
  }
  object Chile {
    type Continental = Continental.type
    type EasterIsland = EasterIsland.type
    implicit object Continental extends TimeZone(id = "Chile/Continental")
    implicit object EasterIsland extends TimeZone(id = "Chile/EasterIsland")
  }
  object Artic {
    type Longyearbyen = Longyearbyen.type
    implicit object Longyearbyen extends TimeZone(id = "Arctic/Longyearbyen")
  }
  object Other {
    type Greenwich = Greenwich.type
    type Japan = Japan.type
    type Portugal = Portugal.type
    type Egypt = Egypt.type
    type Israel = Israel.type
    type Libya = Libya.type
    type Iran = Iran.type
    type GBEire = GBEire.type
    type Poland = Poland.type
    type Universal = Universal.type
    type Kwajalein = Kwajalein.type
    type Singapore = Singapore.type
    type Iceland = Iceland.type
    type Turkey = Turkey.type
    type Cuba = Cuba.type
    type Jamaica = Jamaica.type
    type Zulu = Zulu.type
    type Hongkong = Hongkong.type
    type Navajo = Navajo.type
    type Eire = Eire.type
    type UTC = UTC.type
    implicit object Greenwich extends TimeZone(id = "Greenwich")
    implicit object Japan extends TimeZone(id = "Japan")
    implicit object Portugal extends TimeZone(id = "Portugal")
    implicit object Egypt extends TimeZone(id = "Egypt")
    implicit object Israel extends TimeZone(id = "Israel")
    implicit object Libya extends TimeZone(id = "Libya")
    implicit object Iran extends TimeZone(id = "Iran")
    implicit object GBEire extends TimeZone(id = "GB-Eire")
    implicit object Poland extends TimeZone(id = "Poland")
    implicit object Universal extends TimeZone(id = "Universal")
    implicit object Kwajalein extends TimeZone(id = "Kwajalein")
    implicit object Singapore extends TimeZone(id = "Singapore")
    implicit object Iceland extends TimeZone(id = "Iceland")
    implicit object Turkey extends TimeZone(id = "Turkey")
    implicit object Cuba extends TimeZone(id = "Cuba")
    implicit object Jamaica extends TimeZone(id = "Jamaica")
    implicit object Zulu extends TimeZone(id = "Zulu")
    implicit object Hongkong extends TimeZone(id = "Hongkong")
    implicit object Navajo extends TimeZone(id = "Navajo")
    implicit object Eire extends TimeZone(id = "Eire")
    implicit object UTC extends TimeZone(id = "UTC")
  }
}
